### ISSUE TITLE
Intro editing issues

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#726]
Several issues have been reported and require testing (in the upcoming v. 1.3.3)

**Changing the font size in the Intro tab causes the software to crash**. 

This should no longer be happening. Apart from clicking the icon, please verify if the keyboard shortcuts (CTRL+[ and CTRL+]) do not crash either. 

**Click insert diagram [...] Clicking on it will bring back the deleted Diagram (grey board) and flip it.** 

Fixed

**Insert diagram in intro tab and then edit it. If you click the border on the board that appears then the software crashes** 

Fixed

**[...] If you right-click on the pieces outside the board that appears and then left-click on another piece, the software crashes.**

Fixed

**Comment by akaKarthick** [comment]
1. 

https://github.com/czbar/ChessForge/assets/125844120/1f7fcf75-54f7-44d4-8f25-e3dd86eaabe4

2. 
Ctrl+Alt+R= White Rook 
and also Opens Nvidia Performance overlay (Alt+R) 

3. When i try to changing font size, drawing shapes in main board, the software crashes.

**Comment by czbar** [comment]
Re 1: Looks like my recent fixes are causing diagrams to "disappear" in multiple scenarios.  I'll investigate and fix that. 
Re 2: White Rook is just ALT+R (without CTRL) and SHIFT+ALT+R is black rook.  If there is a clash with other software intercepting those shortcuts then there is not much I can do, other than implementing alternative shortcuts or letting the user configure them.
Re 3: Cannot reproduce. Are there any particular steps for this to happen?

**Comment by czbar** [comment]
Re 1: Yes, this is a regression caused by a fix to items 4 and 5 in #716.  I put in place a procedure removing remnants of deleted diagrams so that they can't be clicked. However, that procedure is triggered from some wrong contexts and that will be difficult to address.  I have to take a different approach and leave those "remnants" in place but disable the click event on them.  Hope that will work perfectly but I would like to ask you to re-tests once I have published the next private build (1.3.4)

**Comment by czbar** [comment]
UPDATE:
Item 1: fixed in v. 1.3.4 https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi
Item 2: needs discussion
Item 3: cannot reproduce

**Comment by akaKarthick** [comment]
yes. Performance overlay intercpting when i click Alt+R. 

![IMG_2023-09-29-14-41-55-358](https://github.com/czbar/ChessForge/assets/125844120/3063c414-0ed2-43d9-9b6f-38481bdb3e2f)

3. 
https://youtu.be/Z3JZZRX8wQI

**Comment by czbar** [comment]
Makes sense.  In my code I'm just checking that the ALT special key is pressed and don't check for other keys.  NVidia clearly checks for CTRL not being pressed at the same time. So, I guess, you have found a neat workaround.

So, is there anything for me to do here, or just mention the potential problem and the "workaround" in Help?  People may have all sorts of stuff intercepting keyboard shortcuts so I don't think there is a universal solution.

**Comment by akaKarthick** [comment]
Performanace overlay is opening even if i press ctrl+alt+R. So we cant do anything. Im just letting you know. If we cant do anything about this, then lets ignore this.   

Btw, you missed 3 rd bug.

**Comment by czbar** [comment]
Indeed, i did miss the last video.  Before, I was trying to reproduce by clicking the icons over the Intro rather than in the main bar!

Now, I can repro and I can immediately see the problem in the code.  Easy fix.  Thank you!

**Comment by czbar** [comment]
Fixed in 1.3.5 https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

**Comment by akaKarthick** [comment]
![Screenshot (3)](https://github.com/czbar/ChessForge/assets/125844120/cd6e363e-f386-4208-b5ac-cc76a3144be8)

i think there is no need for engine in intro.

**Comment by czbar** [comment]
Agreed. I actually have it already of my short list of tweaks to implement.

Btw be aware that there is an issue in saving Intro when AutoSave is on.  I only diagnosed it (and fixed for the next version) today.  Changes to the Intro may not be saved at all if AutoSave is on.

**Comment by akaKarthick** [comment]
https://youtu.be/xobk7MAQefM?si=RWIO2_y5khBtmU3F

**Comment by czbar** [comment]
Great find! Fixed in the next version.

DEBUG: when no move is selected (**internally** - see below) in the view and you navigate away and then back, the program sets an empty line as the "active" line and confuses things. In particular, in your example, you could move a white piece again but not a black one!

Note that **internally**, there is almost always a selection even if the user does not see it. When nothing appears selected to the user, in fact, **internally**, the start position ("position 0") is selected. However, in your scenario, at the very start of the New Workbook processing nothing is selected even internally and that was the bug!

**Comment by czbar** [comment]
Fixed in 1.3.6 (https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi)
